
/**
 * SUPABASE DATABASE SCHEMA
 * 
 * -- Orders Table
 * CREATE TABLE orders (
 *   id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 *   customer_name TEXT NOT NULL,
 *   phone TEXT,
 *   service_type TEXT NOT NULL,
 *   details TEXT,
 *   message TEXT,
 *   created_at TIMESTAMPTZ DEFAULT NOW()
 * );
 * 
 * -- Testimonials Table
 * CREATE TABLE testimonials (
 *   id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 *   name TEXT NOT NULL,
 *   text TEXT NOT NULL,
 *   rating INTEGER CHECK (rating >= 1 AND rating <= 5)
 * );
 * 
 * -- IMPORTANT: Remember to enable RLS and add "Insert" policy for 'orders' 
 * -- and "Select" policy for 'testimonials' in the Supabase Dashboard.
 */

import { createClient } from '@supabase/supabase-js';

const supabaseUrl = 'https://rxetfaomhgjlatjxriny.supabase.co';
const supabaseKey = 'sb_publishable_uyfkHO3DhPhxNHfI7LajqA_8GlIWXRa';

export const supabase = createClient(supabaseUrl, supabaseKey);

export async function saveOrder(orderData: any) {
  try {
    const { data, error } = await supabase
      .from('orders')
      .insert([
        { 
          ...orderData,
          created_at: new Date().toISOString()
        }
      ]);
    if (error) throw error;
    return data;
  } catch (error) {
    console.error('Error saving order to Supabase:', error);
    return null;
  }
}
